name = "KannoSoe"
version = "0.4.0"
defaultTargets = ["KannoSoe"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "KannoSoe"

[[lean_exe]]
name = "glossary_gen"
root = "KannoSoe.Exposition.Gen.Glossary"

[[lean_exe]]
name = "assumptions_gen"
root = "KannoSoe.Exposition.Gen.Assumptions"

[[lean_exe]]
name = "exposition_gen"
root = "KannoSoe.Exposition.Gen.Exposition"

[[lean_exe]]
name = "exposition_generation_full"
root = "KannoSoe.Exposition.Gen.FullExpositionGeneration"
